openapi: 3.0.0
info:
  title: Open Data Service at Elon University
  description: 
    The Open Data Service at Elon University is a service that provides programmatic access to data about Elon University. 
    This service is developed and maintained by the Elon Society of Computing Project Team and is open to active affiliates of the university.
    As this service is still curently in development, endpoints and their responses may change at any time.
  version: 0.0.1
  contact:
    email: ods@elonsoc.org
servers:
  - url: https://ods.elon.edu
    description: Production
  - url: https://odstest.elon.edu
    description: Staging
  - url: http://localhost:3000
    description: Local
tags:
  - name: v1
    description: Version 1 of the API
  - name: Locations
    description: Information about locations on campus
paths:
  /locations/v1/buildings/{building_id}:
    get:
      summary: Get a specific building by ID
      description: Retrieves available building data for sepcified building
      parameters:
        - in: path
          name: building_id
          schema:
            type: string
          required: true
          description: The Building ID
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: API Key
      operationId: GetBuildingById
      tags:
        - v1
        - Locations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Building"
        "401":
          description: API Key provided is not valid.
        "404":
          description: Provided building key is not found.
  /locations/v1/buildings:
    get:
      summary: Get All Buildings
      description: Retrieves available building data for all buildings on campus
      tags:
        - v1
        - Locations
      parameters:
        - in: header
          name: Authorization
          schema:
            type: string
          required: true
          description: API Key
      operationId: GetAllBuildings
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Building"
        "404":
          description: Invalid
        "401":
          description: Unauthorized

components:
  schemas:
    Building:
      type: object
      properties:
        name:
          type: string
          format: string
        floors:
          type: array
          items:
            $ref: "#/components/schemas/Floor"
        location:
          $ref: "#/components/schemas/LatLng"
        address:
          type: string
        type:
          type: string
          enum:
            [
              BuildingTypeUnknown,
              BuildingTypeResidence,
              BuildingTypeDining,
              BuildingTypeOffice,
              BuildingTypeRetail,
              BuildingTypeAcademic,
              BuildingTypeOther,
            ]
        id:
          type: string
          description: The unique id of a building
    LatLng:
      type: object
      properties:
        lat:
          type: number
          format: float64
          description: latitude
        lng:
          type: number
          format: float64
          description: longitude

    Room:
      type: object
      properties:
        name:
          type: string
        level:
          type: integer
    Floor:
      type: object
      properties:
        name:
          type: string
        level:
          type: integer
        Room:
          type: array
          items:
            $ref: "#/components/schemas/Room"